### ISSUE TITLE
No Batching on Transaction Inserts

### ISSUE THREAD

**Issue by thekeviv** [lijunwangs/solana-accountsdb-plugin-postgres#7]
Hi @lijunwangs 

First of all, thank you for your amazing work. I learnt so much from this repo.

I have a question regarding batching on transaction inserts. For accounts, the code batches the SQL queries until it reaches a batch size. It doesn't however do this for transactions. I'm curious if this is for a reason. Is this to minimize latency as the insert won't be made until the batch gets filled? If that's the case, I'm curious why you didn't do this for accounts?

**Comment by lijunwangs** [comment]
The batch insert of accounts actually is only done when the validator starts when we restore the accounts from the snapshots. The batch is done to reduce round trips between the validator the postgres database. It was found significantly reduce the restore time. We did not use batch processing for accounts and transaction at the runtime due to two considerations:
1. The performance seems to be sufficient without doing batch -- batching at the runtime for accounts will be a little more complicated than during the initial start as the same accounts could be updated multiple times -- potentially in the same batch which PostgreSQL does not allow in the same batch. We would have to introduce locking per accounts to do that -- more complicated. To keep it simple, we do not do this.
2. We want to put the transaction and account update ASAP -- some system may require very low latency to see the results. Batching will likely add more delay to it.

**Comment by thekeviv** [comment]
I see it now. Yes, that does make a lot of sense!

Thank you so much!

**Comment by thekeviv** [comment]
Hi @lijunwangs ,

I have a follow up question.

I am still learning Solana and couldn't find this anywhere in docs. Couldn't there be multiple account updates to the same account in snapshots during startup phase as well? Becuase those batch sql inserts would be problematic too?

If you can point me to some place where this is explained more, that would be so much appreciated!

**Comment by lijunwangs** [comment]
No problem, this is due to https://github.com/solana-labs/solana/blob/5a230f418d34a5dd2ea0c8ea8f460379ff2713ee/runtime/src/accounts_db/accountsdb_plugin_utils.rs#L74 -- we ordered the notifications by slot and and within the same slot, we only retain the last write at restore time. Maybe I should update the public doc on it.

**Comment by thekeviv** [comment]
Thank you!

Looking at [this method](https://github.com/solana-labs/solana/blob/5a230f418d34a5dd2ea0c8ea8f460379ff2713ee/runtime/src/accounts_db/accountsdb_plugin_utils.rs#L42), and the method in your comment, if I may summarize, this is my understanding:

We order by slots and then for each slot, add account updates to a return array. If an update on the same account happens again in a different slot, we skip it. Within the same slot, we only take the last write. In short, during the startup phase of validator (when it uses snapshots to update account state), we only save the last account update in the last slot.

**Comment by lijunwangs** [comment]
Yes

**Comment by thekeviv** [comment]
Thank you!
